const i18n = {
  es: {
    "nav.about":"Nosotros","nav.products":"Productos","nav.origins":"Orígenes","nav.contact":"Contacto","nav.cta":"Solicitar información","nav.home":"Inicio",
    "hero.eyebrow":"Cacao de origen · Ecuador & Nicaragua","hero.title":"El mercado del cacao,<br /><em>conectado</em> al origen","hero.sub":"Cacao premium y derivados con trazabilidad garantizada y precios alineados con el mercado internacional. Para la industria alimentaria, fabricantes de chocolate, bean-to-bar y horeca.","hero.btn1":"Ver catálogo","hero.btn2":"Conocer Amari →","hero.s1":"Orígenes premium","hero.s2n":"Grano + Derivados","hero.s2l":"Catálogo completo","hero.s3n":"Trazabilidad","hero.s3l":"De la finca al almacén","hero.s4l":"Industria · Bean-to-bar · Horeca",
    "acceso.eyebrow":"Explora","acceso.title":"Todo sobre <em>Amari</em>","acceso.n1.t":"Nosotros","acceso.n1.p":"Quiénes somos, nuestra misión, visión y los valores que guían cada operación.","acceso.n2.t":"Productos","acceso.n2.p":"Grano de cacao y derivados de Ecuador y Nicaragua para cada tipo de cliente.","acceso.n3.t":"Orígenes","acceso.n3.p":"De dónde viene nuestro cacao y cómo seguimos el mercado en tiempo real.","acceso.n4.t":"Contacto","acceso.n4.p":"Hablemos de cacao. Solicita información, disponibilidad o muestras.","acceso.link":"Ver más",
    "about.eyebrow":"Quiénes somos","about.title":"Experiencia que <em>genera confianza</em>","about.intro":"Amari Cacao nace de la experiencia, la pasión por el cacao y el chocolate, y la convicción de que es posible construir una cadena de suministro más transparente y eficiente. Detrás del proyecto, dos profesionales con amplia trayectoria en el sector.","about.lorena.role":"Fundadora · Selección y origen","about.lorena.bio":"Ligada al mundo de la chocolatería desde el año 2001, ha desarrollado una extensa experiencia en la selección de materias primas, la gestión de proveedores y el trabajo directo con productores en origen. Su labor se centra en la búsqueda de los mejores cacaos, el desarrollo de relaciones sólidas con fincas y cooperativas, y la supervisión de la calidad desde el origen.","about.hector.role":"Director Comercial","about.hector.bio":"Cuenta con una sólida trayectoria en ventas, organización y desarrollo de proyectos comerciales. Es el responsable de la estrategia comercial y del funcionamiento de la plataforma que conecta en tiempo real a productores y clientes de forma eficiente, transparente y dinámica.",
    "mvv.mission.tag":"Misión","mvv.mission.title":"Conexión directa, transparente y eficiente","mvv.mission.text":"Crear una conexión directa entre productores y compradores de cacao, ofreciendo materias primas de calidad, trazabilidad garantizada y una visión actualizada del mercado internacional.","mvv.vision.tag":"Visión","mvv.vision.title":"Plataforma de referencia en Europa","mvv.vision.text":"Convertirnos en la plataforma de referencia para la comercialización de cacao y derivados en Europa, reconocida por su transparencia, cercanía al origen y compromiso con la calidad. Una cadena de valor más equilibrada donde productores, transformadores y clientes crecen juntos.","mvv.purpose.tag":"Propósito","mvv.purpose.title":"Una nueva forma de conectar","mvv.purpose.text":"Hemos creado una nueva forma de conectar productores y compradores: una plataforma basada en la transparencia, el conocimiento del sector y el respeto por quienes cultivan el cacao y quienes lo transforman.",
    "val.1.title":"Transparencia","val.1.text":"Información clara, precios alineados con la realidad del mercado y relaciones honestas.","val.2.title":"Respeto al origen","val.2.text":"Valoramos el trabajo de los productores y fomentamos relaciones duraderas basadas en la confianza.","val.3.title":"Calidad","val.3.text":"Seleccionamos cuidadosamente cada producto para garantizar consistencia y excelencia.","val.4.title":"Compromiso","val.4.text":"Acompañamos a nuestros clientes en cada operación, aportando conocimiento y soluciones.","val.5.title":"Trazabilidad","val.5.text":"Conocemos y controlamos el recorrido de cada producto desde la finca hasta su destino.",
    "sec.eyebrow":"A quién servimos","sec.title":"Soluciones para <em>cada profesional</em>","sec.1.title":"Industria alimentaria","sec.1.text":"Materias primas para fabricantes de chocolate, confitería, panificación, alimentos y bebidas.","sec.2.title":"Empresas semiindustriales","sec.2.text":"Suministros adaptados a transformadores especializados que requieren calidad y flexibilidad.","sec.3.title":"Bean-to-Bar","sec.3.text":"Cacao de origen seleccionado para chocolateros artesanales que buscan productos únicos.","sec.4.title":"Horeca","sec.4.text":"Ingredientes de alta calidad para restauración, pastelería, hostelería y alimentación.",
    "sost.eyebrow":"Sostenibilidad y compromiso","sost.title":"Relaciones que <em>generan futuro</em>","sost.p1":"Creemos que el desarrollo sostenible del sector del cacao depende de relaciones comerciales equilibradas y responsables.","sost.p2":"Por ello fomentamos acuerdos transparentes, promovemos la trazabilidad y trabajamos junto a productores que comparten nuestra visión de crecimiento a largo plazo.","sost.quote":"El respeto por las personas es tan importante como la calidad del producto.","sost.i1.title":"Acuerdos transparentes","sost.i1.text":"Precio claro para el comprador, retribución justa para el productor. Sin intermediarios innecesarios.","sost.i2.title":"Trazabilidad completa","sost.i2.text":"Conocemos el recorrido de cada lote, de la finca al almacén. Documentación disponible para cada partida.","sost.i3.title":"Visión a largo plazo","sost.i3.text":"Construimos relaciones que duran décadas. Con productores, con clientes, con el sector.",
    "prod.eyebrow":"Catálogo","prod.title":"Cacao con <em>identidad propia</em>","prod.intro":"Seleccionamos orígenes reconocidos internacionalmente por su calidad y riqueza sensorial. Grano y derivados adaptados a las necesidades de cada cliente. Venta exclusiva a empresas y fabricantes.","prod.label1":"Grano de cacao","prod.label2":"Derivados de cacao · Ecuador","prod.cta1":"Solicitar oferta →","prod.cta2":"Consultar →",
    "p1.name":"Cacao Premium Ecuador","p1.desc":"Variedad Arriba Nacional, cacao fino de aroma reconocido mundialmente por su perfil aromático complejo, notas florales y excelente potencial para la elaboración de chocolates premium.","p1.tag":"Fino de Aroma","p2.name":"Cacao Premium Nicaragua","p2.desc":"Un origen con gran personalidad, capaz de ofrecer perfiles únicos y diferenciados para proyectos que buscan exclusividad y carácter.","p3.name":"Cacao CCN-51 Ecuador","p3.desc":"Variedad CCN-51 de alto rendimiento, ideal para producción a volumen con perfil consistente. Suministro estable y competitivo para la industria alimentaria.","p3.tag":"CCN-51","p4.name":"Cacao Premium en Grano","p4.desc":"Selección de grano de calidad superior para fabricantes que buscan un perfil diferenciado y un suministro fiable durante toda la campaña.","p4.tag":"Premium","p5.name":"Pasta de Cacao 100%","p5.desc":"La base pura del chocolate, lista para tus creaciones.","p5.tag":"Pasta","p6.name":"Manteca de Cacao","p6.desc":"Pureza y untuosidad para chocolatería y cosmética.","p6.tag":"Manteca","p7.name":"Nibs de Cacao","p7.desc":"El crujiente del cacao en su forma más auténtica.","p8.name":"Cacao en Polvo","p8.desc":"Intensidad y color para repostería y bebidas.","p8.tag":"Polvo",
    "ori.eyebrow":"Orígenes","ori.title":"Donde comienza <em>la calidad</em>","ori.intro":"La calidad de un gran chocolate empieza mucho antes de la transformación. Empieza en el campo, en la selección de variedades y en el conocimiento transmitido de generación en generación.","ori.ec.tag":"Cacao fino de aroma · Reconocido mundialmente","ori.ec.desc":"Uno de los países más reconocidos del mundo por la producción de cacao fino de aroma. Su riqueza genética y sus condiciones naturales permiten obtener perfiles aromáticos únicos apreciados por los fabricantes más exigentes. Nos unimos a productores seleccionados que comparten nuestra pasión por la calidad, la trazabilidad y el cuidado de cada cosecha.","ori.ni.tag":"Fine Flavor · Origen en ascenso","ori.ni.desc":"Un origen en crecimiento que destaca por la calidad de sus granos y por la personalidad de sus perfiles sensoriales. Nos unimos a productores comprometidos con la excelencia y la mejora continua, para dar vida a cacaos diferenciados y de gran valor. Un origen que el mercado europeo está empezando a descubrir.",
    "mkt.eyebrow":"Mercado en tiempo real","mkt.title":"Transparencia que <em>genera confianza</em>","mkt.p1":"El mercado del cacao cambia constantemente. Factores climáticos, productivos y económicos influyen diariamente en la evolución de los precios internacionales.","mkt.p2":"Integramos la realidad del mercado, la evolución de la Bolsa de Nueva York y las necesidades del mercado europeo para ofrecer actualidad y transparencia a productores y compradores.","mkt.b1":"Información actualizada del mercado internacional","mkt.b2":"Conexión directa con el origen","mkt.b3":"Referencias reales de mercado","mkt.live":"En vivo","mkt.consult":"Consultar","mkt.note":"Precios actualizados periódicamente · Solicite acceso a la plataforma",
    "log.eyebrow":"Logística y distribución","log.title":"Soluciones adaptadas <em>a cada cliente</em>","log.p1":"Disponemos de un almacén estratégico en Valencia que nos permite ofrecer rapidez de respuesta y disponibilidad de producto para el mercado europeo.","log.p2":"Para clientes industriales y operaciones de gran volumen, trabajamos directamente desde origen, garantizando una cadena de suministro eficiente.","log.pill1":"Disponibilidad","log.pill2":"Flexibilidad","log.pill3":"Eficiencia logística","log.i1.title":"Almacén Valencia","log.i1.text":"Stock disponible para entrega inmediata en el mercado europeo. Producto listo para producción.","log.i2.title":"Envío desde origen","log.i2.text":"Para grandes volúmenes, operamos directamente desde Ecuador y Nicaragua, optimizando costes y tiempos.","log.i3.title":"Adaptado a cada operación","log.i3.text":"Diferentes volúmenes, formatos y destinos dentro de Europa. Coordinamos la logística completa.",
    "contact.eyebrow":"Contacto","contact.title":"Hablemos de <em>cacao</em>","contact.intro":"Si busca cacao premium, derivados o un proveedor comprometido con la calidad, la trazabilidad y la transparencia, estaremos encantados de ayudarle. Contacte con nuestro equipo para solicitar información, disponibilidad, muestras o propuestas personalizadas.","contact.l1":"Comercial","contact.l2":"Cacao y origen","contact.l3":"Almacén",
    "form.name":"Nombre y empresa","form.name.ph":"Tu nombre y empresa","form.interest":"Producto de interés","form.interest.ph":"Ej: Pasta de cacao Ecuador, 500 kg/mes","form.msg":"Mensaje","form.msg.ph":"Cuéntenos qué necesita…","form.submit":"Enviar consulta",
    "ph.title":"","crumb.home":"Inicio"
  },
  en: {
    "nav.about":"About","nav.products":"Products","nav.origins":"Origins","nav.contact":"Contact","nav.cta":"Request information","nav.home":"Home",
    "hero.eyebrow":"Single-origin cocoa · Ecuador & Nicaragua","hero.title":"The cocoa market,<br /><em>connected</em> to origin","hero.sub":"Premium cocoa and derivatives with guaranteed traceability and prices aligned with international markets. For the food industry, chocolate manufacturers, bean-to-bar and horeca.","hero.btn1":"View catalogue","hero.btn2":"About Amari →","hero.s1":"Premium origins","hero.s2n":"Bean + Derivatives","hero.s2l":"Full catalogue","hero.s3n":"Traceability","hero.s3l":"From farm to warehouse","hero.s4l":"Industry · Bean-to-bar · Horeca",
    "acceso.eyebrow":"Explore","acceso.title":"Everything about <em>Amari</em>","acceso.n1.t":"About","acceso.n1.p":"Who we are, our mission, vision and the values that guide every operation.","acceso.n2.t":"Products","acceso.n2.p":"Cocoa beans and derivatives from Ecuador and Nicaragua for every type of client.","acceso.n3.t":"Origins","acceso.n3.p":"Where our cocoa comes from and how we track the market in real time.","acceso.n4.t":"Contact","acceso.n4.p":"Let's talk cocoa. Request information, availability or samples.","acceso.link":"See more",
    "about.eyebrow":"Who we are","about.title":"Experience that <em>builds trust</em>","about.intro":"Amari Cacao was born from experience, passion for cocoa and chocolate, and the conviction that it is possible to build a more transparent and efficient supply chain. Behind the project, two professionals with extensive track records in the sector.","about.lorena.role":"Founder · Sourcing & origin","about.lorena.bio":"Connected to the world of chocolate making since 2001, she has developed extensive experience in sourcing raw materials, supplier management and direct work with producers at origin. Her work focuses on finding the best cocoas, building solid relationships with farms and cooperatives, and overseeing quality from origin.","about.hector.role":"Commercial Director","about.hector.bio":"With a solid background in sales, organisation and commercial project development. He is responsible for the commercial strategy and the platform that connects producers and clients in real time, efficiently, transparently and dynamically.",
    "mvv.mission.tag":"Mission","mvv.mission.title":"Direct, transparent and efficient connection","mvv.mission.text":"To create a direct connection between cocoa producers and buyers, offering quality raw materials, guaranteed traceability and an up-to-date view of the international market.","mvv.vision.tag":"Vision","mvv.vision.title":"Europe's reference platform","mvv.vision.text":"To become the reference platform for cocoa and derivatives trading in Europe, recognised for its transparency, closeness to origin and commitment to quality. A more balanced value chain where producers, processors and clients grow together.","mvv.purpose.tag":"Purpose","mvv.purpose.title":"A new way to connect","mvv.purpose.text":"We have created a new way to connect producers and buyers: a platform based on transparency, sector knowledge and respect for those who grow cocoa and those who transform it.",
    "val.1.title":"Transparency","val.1.text":"Clear information, prices aligned with market reality and honest relationships.","val.2.title":"Respect for origin","val.2.text":"We value the work of producers and foster lasting relationships based on trust.","val.3.title":"Quality","val.3.text":"We carefully select each product to guarantee consistency and excellence.","val.4.title":"Commitment","val.4.text":"We support our clients in every operation, providing knowledge and solutions.","val.5.title":"Traceability","val.5.text":"We know and control the journey of every product from the farm to its destination.",
    "sec.eyebrow":"Who we serve","sec.title":"Solutions for <em>every professional</em>","sec.1.title":"Food industry","sec.1.text":"Raw materials for chocolate manufacturers, confectionery, baking, food and beverages.","sec.2.title":"Semi-industrial companies","sec.2.text":"Supplies adapted to specialist processors requiring quality and flexibility.","sec.3.title":"Bean-to-Bar","sec.3.text":"Origin-selected cocoa for artisan chocolate makers seeking unique products.","sec.4.title":"Horeca","sec.4.text":"High-quality ingredients for restaurants, pastry, hospitality and food service.",
    "sost.eyebrow":"Sustainability & commitment","sost.title":"Relationships that <em>create the future</em>","sost.p1":"We believe that the sustainable development of the cocoa sector depends on balanced and responsible commercial relationships.","sost.p2":"We therefore promote transparent agreements, traceability and work alongside producers who share our long-term growth vision.","sost.quote":"Respect for people is as important as the quality of the product.","sost.i1.title":"Transparent agreements","sost.i1.text":"Clear pricing for the buyer, fair returns for the producer. No unnecessary intermediaries.","sost.i2.title":"Full traceability","sost.i2.text":"We know the journey of every lot, from farm to warehouse. Documentation available for each batch.","sost.i3.title":"Long-term vision","sost.i3.text":"We build relationships that last decades. With producers, with clients, with the sector.",
    "prod.eyebrow":"Catalogue","prod.title":"Cocoa with <em>its own identity</em>","prod.intro":"We select origins internationally recognised for their quality and sensory richness. Beans and derivatives adapted to each client's needs. Exclusive B2B sales to companies and manufacturers.","prod.label1":"Cocoa beans","prod.label2":"Cocoa derivatives · Ecuador","prod.cta1":"Request offer →","prod.cta2":"Enquire →",
    "p1.name":"Premium Cocoa Ecuador","p1.desc":"Arriba Nacional variety, fine flavour cocoa recognised worldwide for its complex aromatic profile, floral notes and excellent potential for premium chocolate production.","p1.tag":"Fine Flavour","p2.name":"Premium Cocoa Nicaragua","p2.desc":"An origin with great personality, capable of offering unique and differentiated profiles for projects seeking exclusivity and character.","p3.name":"CCN-51 Cocoa Ecuador","p3.desc":"High-yield CCN-51 variety, ideal for volume production with a consistent profile. Stable and competitive supply for the food industry.","p3.tag":"CCN-51","p4.name":"Premium Cocoa Beans","p4.desc":"A selection of superior-quality beans for manufacturers seeking a differentiated profile and reliable supply throughout the season.","p4.tag":"Premium","p5.name":"100% Cocoa Paste","p5.desc":"The pure base of chocolate, ready for your creations.","p5.tag":"Paste","p6.name":"Cocoa Butter","p6.desc":"Purity and smoothness for chocolate and cosmetics.","p6.tag":"Butter","p7.name":"Cocoa Nibs","p7.desc":"The crunch of cocoa in its most authentic form.","p8.name":"Cocoa Powder","p8.desc":"Intensity and colour for pastry and beverages.","p8.tag":"Powder",
    "ori.eyebrow":"Origins","ori.title":"Where <em>quality</em> begins","ori.intro":"The quality of great chocolate begins long before transformation. It begins in the field, in variety selection and in knowledge passed down through generations.","ori.ec.tag":"Fine flavour cocoa · Recognised worldwide","ori.ec.desc":"One of the world's most recognised countries for fine flavour cocoa production. Its genetic richness and natural conditions yield unique aromatic profiles appreciated by the most demanding manufacturers. We join selected producers who share our passion for quality, traceability and the care of every harvest.","ori.ni.tag":"Fine Flavor · Rising origin","ori.ni.desc":"A growing origin that stands out for the quality of its beans and the personality of its sensory profiles. We join producers committed to excellence and continuous improvement, to bring to life differentiated cocoas of great value. An origin that the European market is beginning to discover.",
    "mkt.eyebrow":"Real-time market","mkt.title":"Transparency that <em>builds trust</em>","mkt.p1":"The cocoa market is constantly changing. Climate, production and economic factors influence international price movements daily.","mkt.p2":"We integrate market reality, the evolution of the New York Exchange and European market needs to provide transparency to both producers and buyers.","mkt.b1":"Updated international market information","mkt.b2":"Direct connection to origin","mkt.b3":"Real market references","mkt.live":"Live","mkt.consult":"Enquire","mkt.note":"Periodically updated prices · Request access to the platform",
    "log.eyebrow":"Logistics & distribution","log.title":"Solutions adapted <em>to each client</em>","log.p1":"We have a strategic warehouse in Valencia that allows us to offer fast response times and product availability for the European market.","log.p2":"For industrial clients and high-volume operations, we work directly from origin, guaranteeing an efficient supply chain.","log.pill1":"Availability","log.pill2":"Flexibility","log.pill3":"Logistic efficiency","log.i1.title":"Valencia warehouse","log.i1.text":"Stock available for immediate delivery to the European market. Product ready for production.","log.i2.title":"Shipment from origin","log.i2.text":"For large volumes, we operate directly from Ecuador and Nicaragua, optimising costs and lead times.","log.i3.title":"Adapted to each operation","log.i3.text":"Different volumes, formats and destinations across Europe. We coordinate the full logistics.",
    "contact.eyebrow":"Contact","contact.title":"Let's talk <em>cocoa</em>","contact.intro":"If you are looking for premium cocoa, derivatives or a supplier committed to quality, traceability and transparency, we would be delighted to help. Contact our team to request information, availability, samples or personalised proposals.","contact.l1":"Sales","contact.l2":"Cocoa & origin","contact.l3":"Warehouse",
    "form.name":"Name and company","form.name.ph":"Your name and company","form.interest":"Product of interest","form.interest.ph":"E.g.: Ecuador cocoa paste, 500 kg/month","form.msg":"Message","form.msg.ph":"Tell us what you need…","form.submit":"Send enquiry",
    "crumb.home":"Home"
  }
};
function setLang(lang){
  localStorage_safe(lang);
  document.documentElement.lang=lang;
  document.querySelectorAll('.lang-btn').forEach(b=>b.classList.toggle('active',b.textContent.trim()===lang.toUpperCase()));
  document.querySelectorAll('[data-i18n]').forEach(el=>{const v=i18n[lang][el.getAttribute('data-i18n')];if(v!==undefined)el.innerHTML=v;});
  document.querySelectorAll('[data-i18n-ph]').forEach(el=>{const v=i18n[lang][el.getAttribute('data-i18n-ph')];if(v!==undefined)el.placeholder=v;});
}
// Avoid localStorage (not allowed in some sandboxes) — use a cookie fallback
function localStorage_safe(lang){
  try{document.cookie='amari_lang='+lang+';path=/;max-age=31536000';}catch(e){}
}
function getLang(){
  try{const m=document.cookie.match(/amari_lang=(es|en)/);return m?m[1]:'es';}catch(e){return 'es';}
}
document.addEventListener('DOMContentLoaded',()=>{
  setLang(getLang());
  const obs=new IntersectionObserver((e)=>{e.forEach(x=>{if(x.isIntersecting){x.target.classList.add('vis');obs.unobserve(x.target);}})},{threshold:0.06});
  document.querySelectorAll('.fa').forEach(el=>obs.observe(el));
});
